CAPS_WORD_ENABLE = yes
CUSTOM_MATRIX = lite
WS2812_DRIVER = vendor
RGBLIGHT_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
# NKRO_ENABLE = no # this is already defined at keyboard.json (while QMK is still referring to this as info.json)
SRC += encoder.c
SRC += ghosting.c
SRC += matrix.c
